"""
One-time codegen script: regenerates src/calcflow/constants/ptable.py from
the two source CSVs:
  - src/calcflow/constants/pubchem.csv   (atomic_mass, vdW radius)
  - src/calcflow/constants/pyykkko.csv   (covalent radii r1/r2/r3, Pyykkö 2009)

Run from the project root:
    python scripts/generate_ptable.py

Overwrites src/calcflow/constants/ptable.py in place.
"""

import csv
from pathlib import Path

ROOT = Path(__file__).parent.parent
CONSTANTS = ROOT / "src" / "calcflow" / "constants"
OUT = CONSTANTS / "ptable.py"


def _int_or_none(s: str) -> int | None:
    s = s.strip()
    return int(s) if s else None


def _float_or_none(s: str) -> float | None:
    s = s.strip()
    return float(s) if s else None


# --- load pubchem ---
pubchem: dict[int, dict] = {}
with open(CONSTANTS / "pubchem.csv") as f:
    for row in csv.DictReader(f):
        z = int(row["AtomicNumber"])
        pubchem[z] = {
            "symbol": row["Symbol"].strip(),
            "atomic_mass": _float_or_none(row["AtomicMass"]),
            "atomic_radius_vdw_pm": _int_or_none(row["AtomicRadius"]),
        }

# --- load pyykkko ---
pyykko: dict[int, dict] = {}
with open(CONSTANTS / "pyykkko.csv") as f:
    for row in csv.DictReader(f):
        z = int(row["z"])
        pyykko[z] = {
            "r1": _int_or_none(row["r1"]),
            "r2": _int_or_none(row["r2"]),
            "r3": _int_or_none(row["r3"]),
        }

# --- merge on atomic number ---
all_z = sorted(set(pubchem) | set(pyykko))

lines: list[str] = []
lines.append('"""Module defining element data structures.')
lines.append("")
lines.append("This file is generated by scripts/generate_ptable.py.")
lines.append("Do not edit manually — run the script to regenerate.")
lines.append('"""')
lines.append("")
lines.append("from dataclasses import dataclass")
lines.append("from typing import Final")
lines.append("")
lines.append("")
lines.append("@dataclass(frozen=True)")
lines.append("class Element:")
lines.append('    """Represents a chemical element with essential properties.')
lines.append("")
lines.append("    Attributes:")
lines.append("        atomic_number: The atomic number (number of protons).")
lines.append('        symbol: The chemical symbol (e.g., "H", "C").')
lines.append("        atomic_mass: Standard atomic weight (unified atomic mass units).")
lines.append("        atomic_radius_vdw_pm: Van der Waals radius in pm (PubChem).")
lines.append("        covalent_radius_single_pm: Single-bond covalent radius in pm (Pyykkö 2009).")
lines.append("        covalent_radius_double_pm: Double-bond covalent radius in pm (Pyykkö 2009).")
lines.append("        covalent_radius_triple_pm: Triple-bond covalent radius in pm (Pyykkö 2009).")
lines.append('    """')
lines.append("")
lines.append("    atomic_number: int")
lines.append("    symbol: str")
lines.append("    atomic_mass: float | None")
lines.append("    atomic_radius_vdw_pm: int | None")
lines.append("    covalent_radius_single_pm: int | None")
lines.append("    covalent_radius_double_pm: int | None")
lines.append("    covalent_radius_triple_pm: int | None")
lines.append("")
lines.append("")
lines.append("# A registry mapping uppercase element symbols to Element instances.")
lines.append("# Generated from pubchem.csv (atomic mass, vdW radius) and")
lines.append("# pyykkko.csv (Pyykkö 2009 covalent radii).")
lines.append("ELEMENT_DATA: Final[dict[str, Element]] = {")

for z in all_z:
    pc = pubchem.get(z, {})
    py = pyykko.get(z, {})
    symbol = pc.get("symbol", py.get("symbol", f"X{z}"))
    atomic_mass = pc.get("atomic_mass")
    vdw = pc.get("atomic_radius_vdw_pm")
    r1 = py.get("r1")
    r2 = py.get("r2")
    r3 = py.get("r3")

    def fmt(v):
        return str(v) if v is not None else "None"

    lines.append(
        f'    "{symbol.upper()}": Element('
        f"atomic_number={z}, symbol={symbol!r}, "
        f"atomic_mass={fmt(atomic_mass)}, "
        f"atomic_radius_vdw_pm={fmt(vdw)}, "
        f"covalent_radius_single_pm={fmt(r1)}, "
        f"covalent_radius_double_pm={fmt(r2)}, "
        f"covalent_radius_triple_pm={fmt(r3)}),"
    )

lines.append("}")
lines.append("")

OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({len(all_z)} elements)")
